name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Grant write permissions to the repository contents
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node index.js

      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          # Using exit 0 ensures the workflow finishes successfully even if there are no updates
          git commit -m "Auto update playlist" || { echo "No changes to commit"; exit 0; }
          git push
